
# LOCAL REQUEST FOR CARS


### Get all cars
GET http://localhost:3000/cars HTTP/1.1

### Get car by id
GET http://localhost:3000/cars/64535815fca8687c4e70bfdd HTTP/1.1

### Create car
POST http://localhost:3000/cars HTTP/1.1
content-type: application/json

{
     "make": "hyundai",
    "model": "elantra",
    "trim": "limited",
    "year": "2012",
    "driveType": "awd",
    "color": "blue",
    "titleType": "clean",
    "miles": "100000",
    "transmissionType": "automatic",
    "carType": "car"
}

### PUT car
PUT http://localhost:3000/cars/64535815fca8687c4e70bfdd HTTP/1.1
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "trim": "limited",
    "year": "2020",
    "driveType": "awd",
    "color": "negro",
    "titleType": "clean",
    "miles": "20000",
    "transmissionType": "automatic",
    "carType": "car"
}
### DELETE car
DELETE http://localhost:3000/cars/ HTTP/1.1



# LOCAL REQUEST FOR RESTAURANTS


### Get all restaurants
GET http://localhost:3000/restaurants HTTP/1.1

### Get restaurant by id
GET http://localhost:3000/restaurants/64547098e2193387e9200821 HTTP/1.1

### Create restaurants
POST http://localhost:3000/restaurants HTTP/1.1
content-type: application/json

{
  "name": "Wendy",
  "address": "50 e 300 n",
  "phone": "7058049533",
  "email": "wendy@gmail.com",
  "website": "wendy.com"
}

### PUT restaurant
PUT http://localhost:3000/restaurants/64547098e2193387e9200821 HTTP/1.1
content-type: application/json

{
  "name": "Macdonald",
  "address": "18 e 20 n",
  "phone": "8018016485",
  "email": "mc@gmail.com",
  "website": "macdonald.com"
}
### DELETE restaurant
DELETE http://localhost:3000/restaurants/ HTTP/1.1






// Cars Swagger Deploy 




### Get all cars
GET https://cse341-node-project.onrender.com/cars


### Get car by id
GET https://cse341-node-project.onrender.com/cars/64535815fca8687c4e70bfdd


### Create car
POST https://cse341-node-project.onrender.com/cars HTTP/1.1
content-type: application/json

{
    "make": "hyundai",
    "model": "elantra",
    "trim": "limited",
    "year": "2012",
    "driveType": "awd",
    "color": "blue",
    "titleType": "clean",
    "miles": "100000",
    "transmissionType": "automatic",
    "carType": "car"
}


### PUT car
PUT https://cse341-node-project.onrender.com/cars/64535815fca8687c4e70bfdd HTTP/1.1
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "trim": "limited",
    "year": "2020",
    "driveType": "awd",
    "color": "negro",
    "titleType": "clean",
    "miles": "20000",
    "transmissionType": "automatic",
    "carType": "car"
}


### DELETE car
DELETE https://cse341-node-project.onrender.com/cars/ HTTP/1.1




// Restaurants Swagger Deploy 




### Get all restaurants
GET https://cse341-node-project.onrender.com/restaurants


### Get restaurant by id
GET https://cse341-node-project.onrender.com/restaurants/64547098e2193387e9200821


### Create restaurant
POST https://cse341-node-project.onrender.com/restaurants HTTP/1.1
content-type: application/json

{
  "name": "Wendy",
  "address": "50 e 300 n",
  "phone": "7058049533",
  "email": "wendy@gmail.com",
  "website": "wendy.com"
}


### PUT restaurant
PUT https://cse341-node-project.onrender.com/restaurants/64547098e2193387e9200821 HTTP/1.1
content-type: application/json

{
  "name": "Macdonald",
  "address": "18 e 20 n",
  "phone": "8018016485",
  "email": "mc@gmail.com",
  "website": "macdonald.com"
}


### DELETE restaurant
DELETE https://cse341-node-project.onrender.com/restaurant/ HTTP/1.1